name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "Breaking Changes"
    labels:
      - breaking
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: ⛔️ Deprecated
    labels:
      - deprecated
  - title: 🔐 Security updates
    labels:
      - security
  - title: ⚠️ Maintenance
    labels:
      - chore
      - maintenance
  - title: 📄 Documentation
    labels:
      - docs
      - documentation
  - title: 🧩 Dependency Updates
    labels:
      - deps
      - dependencies
    collapse-after: 5
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels:
  - "skip-changelog"
version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - feature
      - enhancement
  patch:
    labels:
      - "bug"
      - "maintenance"
      - "chore"
      - "dependencies"
      - "deps"
      - "security"
      - "docs"
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
