name: Label Checker

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  check_cc_labels:
    name: Check conventional commits labels
    runs-on: "ubuntu-latest"
    steps:
      - uses: danielchabr/pr-labels-checker@v3.3
        with:
          hasSome: feature,breaking,bug,dependencies,deps,security,docs,documnetation,chore,fix
          githubToken: ${{ secrets.GITHUB_TOKEN }}
